// Industry options
export const industries = [
  { value: 'beauty', label: 'Beauty & Cosmetics' },
  { value: 'fitness', label: 'Fitness & Wellness' },
  { value: 'healthcare', label: 'Healthcare & Medical' },
  { value: 'salon', label: 'Hair Salon & Barber' },
  { value: 'spa', label: 'Spa & Massage' },
  { value: 'therapy', label: 'Therapy & Counseling' },
  { value: 'dental', label: 'Dental' },
  { value: 'veterinary', label: 'Veterinary' },
  { value: 'legal', label: 'Legal Services' },
  { value: 'consulting', label: 'Consulting' },
  { value: 'coaching', label: 'Coaching' },
  { value: 'education', label: 'Education & Tutoring' },
  { value: 'photography', label: 'Photography' },
  { value: 'automotive', label: 'Automotive Services' },
  { value: 'home-services', label: 'Home Services' },
  { value: 'cleaning', label: 'Cleaning Services' },
  { value: 'pet-care', label: 'Pet Care' },
  { value: 'personal-training', label: 'Personal Training' },
  { value: 'yoga', label: 'Yoga & Meditation' },
  { value: 'nail-salon', label: 'Nail Salon' },
  { value: 'tattoo', label: 'Tattoo & Piercing' },
  { value: 'other', label: 'Other' },
]

// Timezone options with common timezones
export const timezones = [
  { value: 'Africa/Lagos', label: 'Africa/Lagos (WAT - UTC+1)' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (SAST - UTC+2)' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo (EET - UTC+2)' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi (EAT - UTC+3)' },
  { value: 'Africa/Casablanca', label: 'Africa/Casablanca (WEST - UTC+1)' },
  { value: 'Africa/Accra', label: 'Africa/Accra (GMT - UTC+0)' },
  { value: 'Africa/Addis_Ababa', label: 'Africa/Addis Ababa (EAT - UTC+3)' },
  { value: 'Africa/Algiers', label: 'Africa/Algiers (CET - UTC+1)' },
  { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar es Salaam (EAT - UTC+3)' },
  { value: 'Africa/Khartoum', label: 'Africa/Khartoum (CAT - UTC+2)' },
  { value: 'Africa/Tunis', label: 'Africa/Tunis (CET - UTC+1)' },
  { value: 'America/New_York', label: 'America/New York (EST - UTC-5)' },
  { value: 'America/Chicago', label: 'America/Chicago (CST - UTC-6)' },
  { value: 'America/Denver', label: 'America/Denver (MST - UTC-7)' },
  { value: 'America/Los_Angeles', label: 'America/Los Angeles (PST - UTC-8)' },
  { value: 'America/Toronto', label: 'America/Toronto (EST - UTC-5)' },
  { value: 'America/Mexico_City', label: 'America/Mexico City (CST - UTC-6)' },
  { value: 'America/Sao_Paulo', label: 'America/São Paulo (BRT - UTC-3)' },
  { value: 'Europe/London', label: 'Europe/London (GMT - UTC+0)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (CET - UTC+1)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (CET - UTC+1)' },
  { value: 'Europe/Rome', label: 'Europe/Rome (CET - UTC+1)' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid (CET - UTC+1)' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam (CET - UTC+1)' },
  { value: 'Europe/Stockholm', label: 'Europe/Stockholm (CET - UTC+1)' },
  { value: 'Europe/Dublin', label: 'Europe/Dublin (GMT - UTC+0)' },
  { value: 'Europe/Athens', label: 'Europe/Athens (EET - UTC+2)' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow (MSK - UTC+3)' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (GST - UTC+4)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (IST - UTC+5:30)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore (SGT - UTC+8)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (JST - UTC+9)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (CST - UTC+8)' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong Kong (HKT - UTC+8)' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok (ICT - UTC+7)' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul (KST - UTC+9)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney (AEDT - UTC+11)' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne (AEDT - UTC+11)' },
  { value: 'Australia/Brisbane', label: 'Australia/Brisbane (AEST - UTC+10)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland (NZDT - UTC+13)' },
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
]
